CREATE TABLE recurring_incomes (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    name VARCHAR(180) NOT NULL,
    description VARCHAR(255),
    amount DECIMAL(19, 2) NOT NULL,
    category_id CHAR(36),
    account_id CHAR(36) NOT NULL,
    receive_day INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    recurrence VARCHAR(20) NOT NULL,
    last_received_year INT NULL,
    last_received_month INT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_recurring_incomes_user_id (user_id),
    CONSTRAINT chk_recurring_incomes_receive_day CHECK (receive_day BETWEEN 1 AND 31),
    CONSTRAINT fk_recurring_incomes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_recurring_incomes_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_recurring_incomes_account FOREIGN KEY (account_id) REFERENCES financial_accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
