CREATE TABLE purchases (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    description VARCHAR(255) NOT NULL,
    purchase_date DATE NOT NULL,
    total_amount DECIMAL(19, 2) NOT NULL,
    category_id CHAR(36),
    location_id CHAR(36),
    payment_method VARCHAR(30) NOT NULL,
    financial_account_id CHAR(36),
    credit_card_id CHAR(36),
    notes VARCHAR(1000),
    number_of_installments INT NOT NULL DEFAULT 1,
    installment_amount DECIMAL(19, 2),
    first_installment_date DATE,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_purchases_user_id (user_id),
    KEY idx_purchases_date (purchase_date),
    KEY idx_purchases_category_id (category_id),
    KEY idx_purchases_account_id (financial_account_id),
    KEY idx_purchases_credit_card_id (credit_card_id),
    KEY idx_purchases_location_id (location_id),
    CONSTRAINT fk_purchases_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_purchases_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_purchases_location FOREIGN KEY (location_id) REFERENCES purchase_locations (id),
    CONSTRAINT fk_purchases_account FOREIGN KEY (financial_account_id) REFERENCES financial_accounts (id),
    CONSTRAINT fk_purchases_credit_card FOREIGN KEY (credit_card_id) REFERENCES credit_cards (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE purchase_items (
    id CHAR(36) NOT NULL,
    purchase_id CHAR(36) NOT NULL,
    product_id CHAR(36),
    quantity DECIMAL(19, 3) NOT NULL,
    unit_price DECIMAL(19, 2) NOT NULL,
    total_price DECIMAL(19, 2) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_purchase_items_purchase_id (purchase_id),
    KEY idx_purchase_items_product_id (product_id),
    CONSTRAINT fk_purchase_items_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_items_product FOREIGN KEY (product_id) REFERENCES products (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE installments (
    id CHAR(36) NOT NULL,
    purchase_id CHAR(36) NOT NULL,
    installment_number INT NOT NULL,
    total_installments INT NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_at DATETIME(6),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_installments_purchase_id (purchase_id),
    KEY idx_installments_due_date (due_date),
    KEY idx_installments_status (status),
    CONSTRAINT fk_installments_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
