CREATE TABLE investments (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    name VARCHAR(180) NOT NULL,
    institution VARCHAR(120),
    type VARCHAR(30) NOT NULL,
    ticker VARCHAR(30),
    current_value DECIMAL(19, 2) NOT NULL DEFAULT 0,
    quantity DECIMAL(19, 8) NOT NULL DEFAULT 0,
    total_invested DECIMAL(19, 2) NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_investments_user_id (user_id),
    CONSTRAINT fk_investments_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE investment_transactions (
    id CHAR(36) NOT NULL,
    investment_id CHAR(36) NOT NULL,
    account_id CHAR(36),
    type VARCHAR(20) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    quantity DECIMAL(19, 8),
    price DECIMAL(19, 8),
    transaction_date DATE NOT NULL,
    notes VARCHAR(1000),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_investment_tx_investment_id (investment_id),
    KEY idx_investment_tx_date (transaction_date),
    KEY idx_investment_tx_account_id (account_id),
    CONSTRAINT fk_investment_tx_investment FOREIGN KEY (investment_id) REFERENCES investments (id),
    CONSTRAINT fk_investment_tx_account FOREIGN KEY (account_id) REFERENCES financial_accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE recurring_expenses (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    name VARCHAR(180) NOT NULL,
    description VARCHAR(255),
    amount DECIMAL(19, 2) NOT NULL,
    category_id CHAR(36),
    account_id CHAR(36),
    due_day INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    recurrence VARCHAR(20) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_recurring_expenses_user_id (user_id),
    CONSTRAINT chk_recurring_due_day CHECK (due_day BETWEEN 1 AND 31),
    CONSTRAINT fk_recurring_expenses_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_recurring_expenses_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_recurring_expenses_account FOREIGN KEY (account_id) REFERENCES financial_accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE subscriptions (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    name VARCHAR(180) NOT NULL,
    description VARCHAR(255),
    amount DECIMAL(19, 2) NOT NULL,
    category_id CHAR(36),
    payment_method VARCHAR(30) NOT NULL,
    account_id CHAR(36),
    credit_card_id CHAR(36),
    billing_day INT NOT NULL,
    start_date DATE NOT NULL,
    next_billing_date DATE,
    recurrence VARCHAR(20) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    cancelled_at DATETIME(6),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_subscriptions_user_id (user_id),
    KEY idx_subscriptions_next_billing (next_billing_date),
    CONSTRAINT chk_subscription_billing_day CHECK (billing_day BETWEEN 1 AND 31),
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_subscriptions_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_subscriptions_account FOREIGN KEY (account_id) REFERENCES financial_accounts (id),
    CONSTRAINT fk_subscriptions_credit_card FOREIGN KEY (credit_card_id) REFERENCES credit_cards (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
