CREATE TABLE financial_transactions (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    type VARCHAR(20) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    transaction_date DATE NOT NULL,
    description VARCHAR(255),
    account_id CHAR(36),
    credit_card_id CHAR(36),
    category_id CHAR(36),
    purchase_id CHAR(36),
    installment_id CHAR(36),
    income_id CHAR(36),
    investment_transaction_id CHAR(36),
    transfer_id CHAR(36),
    counts_in_monthly_result TINYINT(1) NOT NULL DEFAULT 1,
    affects_account_balance TINYINT(1) NOT NULL DEFAULT 1,
    inflow TINYINT(1) NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_user_id (user_id),
    KEY idx_ft_transaction_date (transaction_date),
    KEY idx_ft_user_date_type (user_id, transaction_date, type),
    KEY idx_ft_category_id (category_id),
    KEY idx_ft_account_id (account_id),
    KEY idx_ft_credit_card_id (credit_card_id),
    KEY idx_ft_purchase_id (purchase_id),
    KEY idx_ft_installment_id (installment_id),
    KEY idx_ft_income_id (income_id),
    KEY idx_ft_transfer_id (transfer_id),
    KEY idx_ft_investment_tx_id (investment_transaction_id),
    CONSTRAINT fk_ft_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_ft_account FOREIGN KEY (account_id) REFERENCES financial_accounts (id),
    CONSTRAINT fk_ft_credit_card FOREIGN KEY (credit_card_id) REFERENCES credit_cards (id),
    CONSTRAINT fk_ft_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_ft_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_ft_installment FOREIGN KEY (installment_id) REFERENCES installments (id),
    CONSTRAINT fk_ft_income FOREIGN KEY (income_id) REFERENCES incomes (id),
    CONSTRAINT fk_ft_investment_tx FOREIGN KEY (investment_transaction_id) REFERENCES investment_transactions (id),
    CONSTRAINT fk_ft_transfer FOREIGN KEY (transfer_id) REFERENCES transfers (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
